# -*- coding: utf-8 -*-
"""PersonaForgeAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWihldLUh5pyID381FjQPMpv8-8T39h-
"""

!pip install transformers torch detoxify sentencepiece -q

import torch
from transformers import pipeline, AutoTokenizer
from detoxify import Detoxify

device = 0 if torch.cuda.is_available() else -1
print(f"🖥️ Using {'GPU' if device == 0 else 'CPU'}")

print("⏳ Loading models...")

# ✅ TinyLlama — small, fast, actually follows instructions
MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

generator = pipeline(
    "text-generation",
    model=MODEL_NAME,
    tokenizer=tokenizer,
    device=device,
    torch_dtype=torch.float16 if device == 0 else torch.float32
)

sentiment = pipeline(
    "sentiment-analysis",
    device=device,
    truncation=True,
    max_length=512
)

toxicity_model = Detoxify('original')
print("🔥 PersonaForge AI Ready!")

# ============================================================
# 🔧 CELL 3 — Core Functions
# ============================================================

def generate_persona(name, profession, mood, background):
    # TinyLlama uses ChatML format
    messages = [
        {"role": "system", "content": "You are a creative character writer. Write vivid, detailed personality profiles."},
        {"role": "user", "content": (
            f"Write a personality profile for:\n"
            f"Name: {name}\n"
            f"Profession: {profession}\n"
            f"Mood: {mood}\n"
            f"Background: {background}\n"
            f"Describe their personality traits, speaking style, and behavior in 3-4 sentences."
        )}
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    output = generator(prompt, max_new_tokens=150, do_sample=True, temperature=0.9,
                       pad_token_id=tokenizer.eos_token_id)
    full_text = output[0]['generated_text']
    # Extract only the assistant's reply (after the last <|assistant|> tag)
    reply = full_text.split("<|assistant|>")[-1].strip()
    return reply


def chat_with_persona(persona_description, user_input):
    messages = [
        {"role": "system", "content": f"You are roleplaying as this character:\n{persona_description}\nStay in character at all times."},
        {"role": "user", "content": user_input}
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    response = generator(prompt, max_new_tokens=80, do_sample=True, temperature=0.8,
                         pad_token_id=tokenizer.eos_token_id)
    full_text = response[0]['generated_text']
    # Extract only the assistant's reply
    reply = full_text.split("<|assistant|>")[-1].strip()
    return reply


def analyze_text(text):
    print("\n📊 ANALYSIS REPORT:")
    sent = sentiment(text[:500])[0]
    label_emoji = "😊" if sent['label'] == "POSITIVE" else "😟"
    print(f"  Sentiment : {label_emoji} {sent['label']} (confidence: {sent['score']:.2f})")
    tox = toxicity_model.predict(text)
    tox_score = round(tox['toxicity'], 3)
    print(f"  Toxicity  : {tox_score}")
    if tox_score > 0.5:
        print("  ⚠️  Warning: High toxicity detected!")
    else:
        print("  ✅ Content appears safe.")
    print("-" * 40)

print("=" * 40)
print("   🎭 PERSONAFORGE AI — CREATE YOUR PERSONA")
print("=" * 40)

name       = input("Enter Name       : ")
profession = input("Enter Profession : ")
mood       = input("Enter Mood       : ")
background = input("Enter Background : ")

print("\n⏳ Generating persona...")
persona = generate_persona(name, profession, mood, background)

print("\n🎭 GENERATED PERSONA:\n")
print(persona)
print("\n" + "=" * 40)
print("💬 Start chatting! Type 'exit' to quit.")
print("=" * 40)

# ✅ Fix 5: Clean loop structure
while True:
    try:
        user_input = input("\nYou: ").strip()
        if not user_input:
            continue
        if user_input.lower() == "exit":
            print("👋 Exiting PersonaForge. Goodbye!")
            break

        print("\n⏳ Generating response...")
        response = chat_with_persona(persona, user_input)

        print("\n🤖 Persona Response:\n")
        print(response)
        analyze_text(response)

    except KeyboardInterrupt:
        print("\n👋 Session interrupted. Goodbye!")
        break